CREATE TABLE [dbo].[Account]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(100) NOT NULL, 
    [Currency] INT NOT NULL, 
    [LeadId] INT NOT NULL
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF,
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON
--, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
) ON [PRIMARY]
, CONSTRAINT [UQAccount5E55825B7B2276C4] UNIQUE NONCLUSTERED 
([Currency] ASC )
WITH 
(PAD_INDEX = OFF,
STATISTICS_NORECOMPUTE = OFF, 
IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY])
GO

ALTER TABLE [dbo].[Account]  WITH CHECK ADD  CONSTRAINT [Account_fk0] FOREIGN KEY([LeadId])
REFERENCES [dbo].[Lead] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Account] CHECK CONSTRAINT [Account_fk0]
GO
