CREATE TABLE [dbo].[Account]
(
	[Id] INT identity(1,1) NOT NULL, 
    [Name] NVARCHAR(100) NOT NULL, 
    [Currency] INT NOT NULL, 
    [LeadId] INT NOT NULL

CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
([Id] ASC) WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
 ON [PRIMARY],

 CONSTRAINT [UQAccount5E55825B7B2276C4] UNIQUE NONCLUSTERED 
([Currency],[LeadId] ASC )
WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY],

)
GO

ALTER TABLE [dbo].[Account]  WITH CHECK ADD  CONSTRAINT [Account_fk0] FOREIGN KEY([LeadId])
REFERENCES [dbo].[Lead] ([Id])
ON UPDATE NO ACTION
GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-LeadId] ON [dbo].[Account]
(
	[LeadId] ASC
)
INCLUDE([Id],[Name],[Currency]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO