CREATE TABLE [dbo].[City]
(
	[Id] INT IDENTITY(1,1) NOT NULL ,
	[Name] nvarchar(100) unique NOT NULL

 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
([Id] ASC)
WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]

