CREATE TABLE [dbo].[Lead]
(
	[Id] INT identity(1,1) NOT NULL, 
    [FirstName] NVARCHAR(100) NOT NULL, 
    [LastName] NVARCHAR(100) NOT NULL, 
    [Login] NVARCHAR(100) NOT NULL, 
    [Password] NVARCHAR(1000) NOT NULL, 
    [Email] NVARCHAR(100) NOT NULL, 
    [Phone] NVARCHAR(20) NOT NULL, 
    [BirthDate] DATETIME NOT NULL,
    [CityId] INT NOT NULL,
    [IsDeleted] BIT NOT NULL,

CONSTRAINT [PK_Lead] PRIMARY KEY CLUSTERED 
([Id] ASC) WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
 ON [PRIMARY],

 CONSTRAINT [UQLead5E55825B7B2276C4] UNIQUE NONCLUSTERED 
([Login] ASC )
WITH 
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY],

 CONSTRAINT [UQLeadA9D10534BF185160] UNIQUE NONCLUSTERED 
([Email] ASC )
WITH
(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Lead]  WITH CHECK ADD  CONSTRAINT [Lead_fk0] FOREIGN KEY([CityId])
REFERENCES [dbo].[City] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Lead] CHECK CONSTRAINT [Lead_fk0]
GO