CREATE TABLE [dbo].[Lead_Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LeadId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_LEAD_ROLE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_LeadId_RoleId] UNIQUE NONCLUSTERED 
(
	[LeadId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Lead_Role]  WITH CHECK ADD  CONSTRAINT [Lead_Role_fk0] FOREIGN KEY([LeadId])
REFERENCES [dbo].[Lead] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Lead_Role] CHECK CONSTRAINT [Lead_Role_fk0]
GO

ALTER TABLE [dbo].[Lead_Role]  WITH CHECK ADD  CONSTRAINT [Lead_Role_fk1] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
ON UPDATE NO ACTION
GO

ALTER TABLE [dbo].[Lead_Role] CHECK CONSTRAINT [Lead_Role_fk1]
GO